apiVersion: batch/v1
kind: Job
metadata:
  namespace: dpdemo
  name: dppublisher-job
  
spec:
    template:
        spec:
          restartPolicy: Never          
          containers:
          - name: dppublisher
            image: codebestard/dppublisher:v1
            imagePullPolicy: Always        
            env:
            - name: queuelib
              value: "nats"
            - name: mqConnectionString
              value: "nats://ruser:T0pS3cr3t@137.116.63.119:4222"
            - name: batches
              value: "20"
            - name: batchSize
              value: "10"                    
            resources:
              requests:
                memory: "64Mi"
                cpu: "250m"
              limits:
                memory: "128Mi"
                cpu: "500m"      